import {
  CodeBracketIcon,
  Cog8ToothIcon,
  DocumentDuplicateIcon,
  MagnifyingGlassIcon,
  PlayIcon,
  SquaresPlusIcon,
  UserCircleIcon,
} from '@heroicons/react/24/outline/';
import { type NextPage } from 'next';
import Head from 'next/head';
import { LeftMenuBar } from '../components';
import { useDocumentsStore } from '../stores';
import { clg } from '../utils';

const Home: NextPage = () => {
  // Active tabs
  const activeTabs = useDocumentsStore((state) => state.activeTabs);
  // Active tab
  const activeTab = useDocumentsStore((state) => state.activeTab);
  const setActiveTab = useDocumentsStore((state) => state.setActiveTab);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"> */}
      <main className="relative min-h-screen overflow-hidden bg-slate-900 p-16">
        {/* Window */}
        <div className="relative flex min-h-[900px] rounded-2xl bg-gradient-to-br from-slate-400/40 to-slate-400/0 p-4">
          {/* Icon Indicator Line */}
          <div className="absolute top-[40px] -left-4 h-[1px] w-8 rotate-90 bg-cyan-300 blur-[1px]" />
          {/* Left Icon Bar */}
          <div className="flex flex-col justify-between gap-8 p-2">
            {/* Body */}
            <div className="flex flex-col gap-8">
              <DocumentDuplicateIcon className="h-8 w-8 text-slate-100" />
              <MagnifyingGlassIcon className="h-8 w-8 text-slate-400" />
              <SquaresPlusIcon className="h-8 w-8 text-slate-400" />
              <PlayIcon className="h-8 w-8 text-slate-400" />
            </div>
            {/* Bottom */}
            <div className="flex flex-col gap-4">
              <UserCircleIcon className="h-8 w-8 text-slate-400" />
              <Cog8ToothIcon className="h-8 w-8 text-slate-400" />
            </div>
          </div>
          {/* Left Menu Bar */}
          <LeftMenuBar />
          {/* BODY */}
          <div className="flex flex-col gap-4 p-2">
            {/* TABS */}
            <div className="flex gap-4">
              {activeTabs.map((tab) => (
                <button
                  key={tab}
                  className={clg(
                    'flex items-center gap-2 rounded bg-gradient-to-br from-slate-700/40 to-slate-700/0 p-2 backdrop-blur-sm',
                    {
                      'border-b border-cyan-300': activeTab === tab,
                    },
                    {
                      ' ': activeTab !== tab,
                    }
                  )}
                  onClick={() => setActiveTab(tab)}
                  type="button"
                >
                  <CodeBracketIcon className="h-6 w-6 text-slate-100" />
                  <span className="font-consolas text-base font-normal italic text-slate-100">
                    index.tsx
                  </span>
                </button>
              ))}
            </div>
            {/* EDITOR */}
            <div className="flex py-4">EDITOR</div>
          </div>
        </div>
        {/* Circles */}
        <div className="absolute left-[1066px] top-[315px] h-[100px] w-[100px] rounded-full bg-cyan-300 mix-blend-screen blur-3xl" />
        <div className="absolute left-[395px] top-[741px] h-[100px] w-[100px] rounded-full bg-cyan-300 mix-blend-screen blur-3xl" />
      </main>
    </>
  );
};

export default Home;
// TODO: remove when complete https://codesandbox.io/s/hungry-pine-k7g0y9?file=/src/document.js:166-187
