import { ThemeProvider } from 'next-themes';
import Head from 'next/head';
import { type FunctionComponent, useEffect, useState } from 'react';

interface LayoutProps {
  children: React.ReactElement;
}

const Layout: FunctionComponent<LayoutProps> = ({ children }) => {
  const [isHydrated, setIsHydrated] = useState(false);

  // Wait till NextJS rehydration completes
  useEffect(() => {
    setIsHydrated(true);
  }, []);

  const page = (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="class" enableSystem>
        {children}
      </ThemeProvider>
    </>
  );

  return isHydrated ? page : <div>Loading...</div>;
};

export default Layout;
